### ISSUE TITLE
Review notes

### ISSUE THREAD

**Issue by chrisvfritz** [tessmero/tc359_project9_tessmero#1]
In the `javascripts` and `stylesheets` folders, it looks like you've tried to rename files from `.scss` to `.css` and `.coffee` to `.js`. Instead, we have both versions in this repo. If this is unexpected, you probably just forgot to type `git add -A .` (with the `-A` so that it git stages not only new and modified files, but also file deletions) before committing. Can you make sure we get rid of those files?

I also see a [hard-tab here](https://github.com/tessmero/tc359_project9_tessmero/blob/master/app/assets/stylesheets/static.css#L2). The standard indentation for Ruby (`.rb`) files is two-space soft-tabs. And in Rails projects, it's actually best practice to have *every* file use two-space soft-tabs.

Can you [reconfigure your text editor](https://github.com/chrisvfritz/tc359_cheatsheets/blob/master/ruby/indentation.md) to use two-space soft-tabs instead? And then afterwards, update all your files to use that indentation. You may also find [this video](https://www.youtube.com/watch?v=_JFIeY46sIU) and [this video](https://www.youtube.com/watch?v=GMf8dlrEbB4) helpful for Sublime Text.

Let me know when you've updated these and I'll take another look. If you get stuck, also please don't hesitate to let me know and I'll be happy to point you in the right direction.

**Comment by tessmero** [comment]
fixed

**Comment by chrisvfritz** [comment]
:+1: Looks great!
